### ISSUE TITLE
EEprom Dump mit 1024 Byte wird nicht erkannt (T24C08A Chip)

### ISSUE THREAD

**Issue by Feuerstahl** [adlerweb/UT210E-Calculator#1]
Hallo adlerweb,
ich habe heute versucht den Kalkulator an meinem UT210E mit einem eingebauten T24C08A EEprom anzuwenden.
Der Chip hat einem 1024 Byte großen Speicher.

Der Kalkulator akzeptiert allerdings nur ein Dumpfile mit größe 256 Byte, ansosnten spuckt er folgenden Fehler aus.

File Size != 256 Bytes. Probably no binary EEPROM dump! Aborting!

Interessant ist, daß der Addressbereich 0x00 - 0xFF Daten enthält, und ab Addresse 0x0100 - 0x03FF keine Daten stehen.
So wie es ausschaut sind die für uns wichtigen Informationen im selben Addressbereich zu finden, wie beim  DM24C02A Chip.

Im Anhang ist die Zip mit Screenshots und dem Dumpfile meines noch Jungfräulichen UT210E zu finden, vielleicht lässt sich damit ja was anfangen 

Grüße
Feuerstahl

[T24C08A Ram Backup.zip](https://github.com/adlerweb/UT210E-Calculator/files/7109570/T24C08A.Ram.Backup.zip)
![UT210E _EEprom_dump_1](https://user-images.githubusercontent.com/59896256/132090695-d3666fa1-8c11-4e52-b93c-8db66533520a.PNG)
![UT210E _EEprom_dump_2](https://user-images.githubusercontent.com/59896256/132090697-4102c17c-d442-497b-b6fe-ea12160b53f7.PNG)

**Comment by adlerweb** [comment]
Moin,
ich hab den Code so angepasst, dass er zumindest nicht mehr abbricht. Mit etwas Glück reicht das ja schon.

**Comment by Feuerstahl** [comment]
Servus, 
ich hab es gestern abend noch einmal ausprobiert. 
Die Fehlermeldung kommt, die Datei kann aber eingelesen und angepasst werden. 
Will ich mir das Bin File ausgeben lassen, wird eines mit 256Byte erstellt, soweit ok. 
Ich bin mir jetzt unsicher, wenn ich nur den 256 Byte teil flashe, ob auch nur dieser Teil überschrieben wird.
Sicherheitshalber hab ich von Hand die geänderten Hex-Werte in meine vorhandene .bin eingetragen und in den Speicher runtergeladen.
So hat es jedenfalls funktioniert.

**Comment by NiklasVoigt** [comment]
Ich habe ebenfalls ein UT210E von APR-2021 mit dem T24C08A. Habe ebenfalls festgestellt das der Speicher nur im 256Byte Bereich beschrieben ist. Habe dann in der Software gesagt es ist ein T24C02A, ausgelesen und verifiziert das das selbst drin steht.
Die Somit ausgelesenen 256Bytes kann man auf die alt bekannte Art und Weise modifizieren und auch im T24C02A Mode auf den T24C08A flashen. Alles funktioniert!
